### ISSUE TITLE
Some of solidus_frontend's JS depends on classes removed in this fork

### ISSUE THREAD

**Issue by pedantic-git** [nebulab/solidus_starter_frontend#4]
Hi everyone - thanks so much for this fork that has taken so much of the effort out of implementing a Bootstrap frontend for my store.

I know the goal is to strip out all Skeleton classes, but some of the classes stripped are actually depended on by the JS.

The first example is: https://github.com/solidusio/solidus/blob/master/frontend/app/assets/javascripts/spree/frontend/cart.js#L7

This code expects the line items in the cart to have a class of 'line-item' in order to remove them, but this class has been removed. I'm sure I've seen other examples but I don't have them to hand yet. Something to be aware of, anyway!

**Comment by dinohamzic** [comment]
Hi @pedantic-git. 

Thank you for the feedback and for taking the time to give a look at the code. This extension is still very early stage, and not suitable for any kind of usage outside of its own development.

You are correct in saying that one of the goals is to strip out skeleton classes (we also did some semantic refactoring), but there are also other goals for the near future. One of them is to eliminate jQuery as a dependency by rewriting the current frontend implementation using vanilla JavaScript. This is why we are ignoring JavaScript breaking changes, at least for the time being.

We will improve the readme file to better outline the goals of the project and more importantly to keep track of what has been done and what has to be done.

Cheers!

**Comment by pedantic-git** [comment]
Understood! Thank you for the explanation! It'll be great to ditch jQuery of course, especially if you're moving to a webpacker-based frontend!

I'm still planning to use it myself because the existing solidus_frontend is so unsuitable for my current task. I guess I'll just fix these issues myself when I come across them!

**Comment by dinohamzic** [comment]
@pedantic-git it was a long wait, but we now rewrote the JavaScript and completely ditched jQuery. Closing this issue as it should be fixed now.

**Comment by pedantic-git** [comment]
@dinohamzic That's great to hear! I'm not working on this project any more (as far as I know) but I'll take a look if I ever revive it!
