### ISSUE TITLE
Create docs for getting project up and running for development

### ISSUE THREAD

**Issue by jacquesporveau** [nebulab/solidus_starter_frontend#40]
I think there are some undocumented steps that developers need to take in order to start development on this project.

I went with the usual:

```bash
bundle install
bundle exec rspec
```

and ran into a bunch of errors immediately related mostly to files missing and uninitialized constants.

It looks like there are probably some steps that need to be taken in order to set up the project that aren't documented anywhere. 

Documenting those steps will make on-boarding developers much easier.

**Comment by dinohamzic** [comment]
Thanks for the feedback @jacquesporveau, we agree completely.

We are currently focusing our efforts on the last finishing touches of this rewrite, and we will shorty start improving the documentation.

**Comment by blocknotes** [comment]
Hey @jacquesporveau, we put some development information here:
https://github.com/nebulab/solidus_starter_frontend/blob/master/docs/development.md
