### ISSUE TITLE
uninitialized constant Spree::UserConfirmationsController

### ISSUE THREAD

**Issue by blocknotes** [nebulab/solidus_starter_frontend#96]
Creating a new app from scratch I get the error:
```
solidus_starter_frontend/lib/solidus_starter_frontend/engine.rb:20:in `block in <class:Engine>’: uninitialized constant Spree::UserConfirmationsController (NameError)
```

### Steps to reproduce
- create the Rails app (6.0.3.2): `rails new solidus_test`
- add Solidus to Gemfile:
```
gem 'solidus_core'
gem 'solidus_api'
gem 'solidus_backend'
gem 'solidus_sample'
gem 'solidus_auth_devise'
```
- execute `bundle`
- run the generator `bin/rails g spree:install`
- add the starter to Gemfile:
```
gem 'solidus_starter_frontend'
```
- `mkdir -p app/assets/javascripts/spree/frontend`
- add to *app/assets/javascripts/spree/frontend/all.js*:
```css
//= require spree/frontend/solidus_starter_frontend
```
- `mkdir -p app/assets/stylesheets/spree/frontend`
- add to *app/assets/stylesheets/spree/frontend/all.css*:
```js
/*
 *= require spree/frontend/solidus_starter_frontend
 */
```

**Comment by blocknotes** [comment]
Adding more details:
- the same issue happens with Rails 5.2.4.3
- commenting out the lines that break (`config.to_prepare` in *engine.rb*) and running in console: `Spree::UserConfirmationsController` returns `uninitialized constant` error
- after changing the Gemfile adding `solidus_frontend` gem and removing `solidus_starter_frontend`, running in console: `Spree::UserConfirmationsController` works

**Comment by blocknotes** [comment]
From my investigations:
- editing locally *solidus_sopport* at [this point](https://github.com/solidusio/solidus_support/blob/master/lib/solidus_support.rb#L50) forcing `true` solve the loading error;
- so our override method [here](https://github.com/nebulab/solidus_starter_frontend/blob/master/lib/solidus_starter_frontend/solidus_support_extensions.rb) seems to be called at a wrong point;
- moving our `gem 'solidus_starter_frontend'` in Gemfile before Solidus gems solves the issue.

**Comment by blocknotes** [comment]
Closing this one after the README updates made [here](https://github.com/nebulab/solidus_starter_frontend/pull/110/commits/3e8ee024f2babd2a2d4f37122fde52da10e1eae4).

**Comment by DanielePalombo** [comment]
The links in the previous comment point to the master. 
The right links are:

editing locally solidus_sopport at [this point](https://github.com/solidusio/solidus_support/blob/e65847dd135dbfe762cd1020946990cca854344f/lib/solidus_support.rb#L49-L51) forcing true solve the loading error;
so our override method [here](https://github.com/solidusio/solidus_starter_frontend/blob/c65d3995d90ad3e45cf3425a93cd46f4d6969390/lib/solidus_starter_frontend/solidus_support_extensions.rb#L5) seems to be called at a wrong point if Devise is already loaded;
