### ISSUE TITLE
Install generator doesn't seem to be working

### ISSUE THREAD

**Issue by markmead** [nebulab/solidus_starter_frontend#97]
`gem install solidus_starter_frontend` hits this error `Could not find a valid gem 'solidus_starter_frontend' (>= 0) in any repository`

And the old way of `bundle exec rails g solidus_starter_frontend:install` hits the error `Could not find generator 'solidus_starter_frontend:install'`

**Comment by blocknotes** [comment]
We updated the README before publishing the gem 😅 
Now it's available.

Thank you for @markmead!
